language: android

android:
  components:
    - build-tools-19.0.2

before_install:
 # install inkscape and imagemagick
 - sudo apt-get update -qq
 - sudo apt-get install -qq inkscape imagemagick

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura -pl \!rezenerator-maven-sample
